---
- name: Instalar Apache
  ansible.builtin.package:
    name: httpd
    state: present

- name: Instalar PHP y módulos necesarios
  ansible.builtin.package:
    name: "{{ php_packages }}"
    state: present
  notify: restart apache

- name: Crear directorio DocumentRoot
  ansible.builtin.file:
    path: "{{ apache_vhosts[0].documentroot }}"
    state: directory
    owner: apache
    group: apache
    mode: '0755'

- name: Crear archivo info.php
  ansible.builtin.template:
    src: info.php.j2
    dest: "{{ apache_vhosts[0].documentroot }}/info.php"
    owner: apache
    group: apache
    mode: '0644'

- name: Configurar VirtualHost de Apache
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: "/etc/httpd/conf.d/example.conf"
    owner: root
    group: root
    mode: '0644'
  notify: restart apache

- name: Iniciar y habilitar Apache
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: Configurar firewall para Apache (http/https)
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - http
    - https
  notify: reload firewall
